routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::get('/users', function () {
    return view('chart.user', [
        'title' => 'Active user per day'
    ]);
});
Route::get('/userstotal', function () {
    return view('chart.usertotal', [
        'title' => 'Home'
    ]);
});
Route::get('/usersservices', function () {
    return view('chart.userservices', [
        'title' => 'Home'
    ]);
});
Route::get('/usersdatas', function () {
    return view('chart.usersdatas', [
        'title' => 'Home'
    ]);
});
Route::get('/usersrevenue', function () {
    return view('chart.userrevenue', [
        'title' => 'Home'
    ]);
});
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>'auth'], function(){
	Route::get('/', 'HomeController@index')->name('index');
	Route::get('/normalization/{data}', 'NormalizationController@index');
	Route::group(['prefix'=>'asset', 'as'=>'asset.'], function(){
		Route::resource('products','AssetProductController');
		Route::group(['prefix'=>'products/{product}', 'as'=>'products.'], function(){
			Route::resource('competitors','AssetProductCompetitorController');
		});
		Route::get('data-collections/generate', 'AssetDataCollectionController@generateData');
		Route::resource('data-collections','AssetDataCollectionController');
		Route::resource('models','AssetModelController');
		Route::resource('copy-rights','AssetCopyRightController');
		Route::resource('softwares','AssetSoftwareController');
		Route::resource('insights','AssetInsightController');
		Route::resource('clients','AssetClientController');
		Route::resource('reports','AssetReportController');
		Route::resource('clipping-onlines','AssetClippingOnlineController');
		Route::resource('domains','AssetDomainController');
	});

	Route::group(['namespace'=>'Operasional', 'prefix'=>'operational', 'as'=>'operational.'], function(){
		Route::resource('engine','EngineController');
		Route::resource('database','DatabaseController');
		Route::resource('groupserver','GroupServerController');
		Route::resource('server','ServerController');
		Route::resource('serverxgroup','ServerXGroupController');
		Route::resource('enginexdatabase','EngineXDatabaseController');
		Route::resource('enginexserver','EngineXServerController');
	});

	Route::group(['prefix'=>'ajax', 'namespace'=>'Ajax'], function(){
		Route::get('dashboard/chart-data-collection', 'DashboardController@chartDataCollectionV2');
		Route::get('dashboard/chart-valuasi', 'DashboardController@chartValuasi');
	});
});

app/Models/AssetReport.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\{Model, SoftDeletes};
use Storage;

class AssetReport extends Model
{
    use SoftDeletes;
    protected $guarded = [];

    public function getUrlFileAttribute()
    {
        if($this->file){
            return Storage::disk(config('app.disk'))->url($this->file);
        }
    }

    public function getFileNameAttribute()
    {
        if($this->file){
            $name = collect(explode("/", $this->file));
            return $name->last();
        }
    }

    public function client()
    {
        return $this->belongsTo(AssetClient::class, 'client_id');
    }
}

resources/views/asset/insights/create.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('asset.insights.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>@lang('app.add') @lang('app.insights')</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">@lang('app.assets')</a></div>
          <div class="breadcrumb-item">@lang('app.add') @lang('app.insights')</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Data @lang('app.insights')</h4>
              </div>
              <div class="card-body">
                <form class="form" action="{{ route('asset.insights.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <!-- NAME -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.name')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('name') }}" name="name" class="@error('name') is-invalid @enderror form-control">
                            @error('name')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- CATEGORY -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.category')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('category') }}" name="category" class="@error('category') is-invalid @enderror form-control">
                            @error('category')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- DESCRIPTION -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.description')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <textarea name="description" class="@error('description') is-invalid @enderror form-control" row="3">{{ old('description') }}</textarea>
                            @error('description')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- MONTH -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.month')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            @php
                                $month = ['January','February','March','April','May','June','July','August','September','October','November','December'];
                            @endphp
                            <select class="form-control" name="month" required="">
                                <option value="">-</option>
                                @foreach($month as $key => $item)
                                <option value="{{$key+1}}" {{ old('month') == $key+1 ? 'selected' : ''}}>{{$item}}</option>
                                @endforeach
                            </select>
                            @error('month')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- YEAR -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.year')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <select class="form-control" name="year" required="">
                                <option value="">-</option>
                                @for($i = now()->format('Y'); $i >= 2000; $i--)
                                <option value="{{$i}}" {{ old('year') == $i ? 'selected' : ''}}>{{$i}}</option>
                                @endfor
                            </select>
                            @error('year')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- FILE -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.file')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="file" value="{{ old('file') }}" name="file" class="@error('file') is-invalid @enderror form-control">
                            @error('file')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right"></label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>

                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

@section('js')
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/upload-preview/assets/js/jquery.uploadPreview.min.js') }}"></script>
<script>
    $.uploadPreview({
        input_field: "#image-upload",   // Default: .image-upload
        preview_box: "#image-preview",  // Default: .image-preview
        label_field: "#image-label",    // Default: .image-label
        label_default: "Pilih Foto",   // Default: Choose File
        label_selected: "Ganti Foto",  // Default: Change File
        no_label: false,                // Default: false
        success_callback: null          // Default: null
    });
  </script>
@endsection

resources/views/asset/insights/edit.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('asset.insights.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>@lang('app.edit') @lang('app.insights')</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item"><a href="#">@lang('app.assets')</a></div>
          <div class="breadcrumb-item"><a href="{{ route('asset.insights.index') }}">@lang('app.insights')</a></div>
          <div class="breadcrumb-item">@lang('app.edit') {{ $insight->name }}</div>
        </div>
      </div>
      
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Data @lang('app.insights')</h4>
              </div>
              <div class="card-body">
                <form class="form" action="{{ route('asset.insights.update', $insight->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')

                    <!-- NAME -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.name')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('name', $insight->name) }}" name="name" class="@error('name') is-invalid @enderror form-control">
                            @error('name')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- CATEGORY -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.category')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('category', $insight->category) }}" name="category" class="@error('category') is-invalid @enderror form-control">
                            @error('category')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- DESCRIPTION -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.description')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <textarea name="description" class="@error('description') is-invalid @enderror form-control" row="3">{{ old('description', $insight->description) }}</textarea>
                            @error('description')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- MONTH -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.month')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            @php
                                $month = ['January','February','March','April','May','June','July','August','September','October','November','December'];
                            @endphp
                            <select class="form-control" name="month" required="">
                                <option value="">-</option>
                                @foreach($month as $key => $item)
                                <option value="{{$key+1}}" {{ old('month', $insight->month) == $key+1 ? 'selected' : ''}}>{{$item}}</option>
                                @endforeach
                            </select>
                            @error('month')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- YEAR -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.year')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <select class="form-control" name="year" required="">
                            <option value="">-</option>
                                @for($i = now()->format('Y'); $i >= 2000; $i--)
                                <option value="{{$i}}" {{ old('year', $insight->year) == $i ? 'selected' : ''}}>{{$i}}</option>
                                @endfor
                            </select>
                            @error('year')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- FILE -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.file')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="file" value="{{ old('file', $insight->file) }}" name="file" class="@error('file') is-invalid @enderror form-control">
                            @error('file')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right"></label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

@section('js')
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/upload-preview/assets/js/jquery.uploadPreview.min.js') }}"></script>
<script>
    $.uploadPreview({
        input_field: "#image-upload",   // Default: .image-upload
        preview_box: "#image-preview",  // Default: .image-preview
        label_field: "#image-label",    // Default: .image-label
        label_default: "Pilih Foto",   // Default: Choose File
        label_selected: "Ganti Foto",  // Default: Change File
        no_label: false,                // Default: false
        success_callback: null          // Default: null
    });
  </script>
@endsection

resources/views/asset/insights/index.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>@lang('app.insights')</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">@lang('app.assets')</a></div>
          <div class="breadcrumb-item"><a href="#">@lang('app.insights')</a></div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>@lang('app.list_of') @lang('app.insights')</h4>
              </div>
              <div class="card-body">
                <div class="float-left d-flex">
                    <a href="{{ route('asset.insights.create') }}" class="btn btn-primary">Add @lang('app.insights')</a>
                </div>
                <div class="float-right">
                  <form action="" method="GET">
                    <div class="input-group">
                      <input type="text" class="form-control" name="search" placeholder="Search" value="{{ request()->search }}">
                      <div class="input-group-append">
                        <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                      </div>
                    </div>
                  </form>
                </div>

                <div class="clearfix mb-3"></div>

                <div class="table-responsive">
                  <table class="table table-striped">
                    <tr>
                      <th>No</th>
                      <th>@lang('app.name')</th>
                      <th>@lang('app.category')</th>
                      <th>@lang('app.description')</th>
                      <th>@lang('app.month')</th>
                      <th>@lang('app.file')</th>
                      <th>@lang('app.year')</th>
                      <th>Opsi</th>
                    </tr>
                    @forelse ($insights as $item)
                    <tr>
                        <td>{{ (($insights->currentPage()-1) * $insights->perPage()) + $loop->iteration }}</td>
                        <td>{{ $item->name }}</td>
                        <td>{{ $item->category }}</td>
                        <td>{{ $item->description }}</td>
                        <td>{{ $item->month }}</td>
                        <td><a href="{{$item->url_file}}" target="_blank">{{ $item->file }}</a></td>
                        <td>{{ $item->year }}</td>
                        <td>
                            <a href="{{ route('asset.insights.show', $item) }}" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Lihat Detail Insight"> <span class="fa fa-eye"></span></a>
                            <a href="{{ route('asset.insights.edit', $item) }}" class="btn btn-sm btn-warning" data-toggle="tooltip" data-placement="top" title="Edit Insight"> <span class="fa fa-edit"></span></a>
                            <span data-title="{{ $item->name }}" href="{{ route('asset.insights.destroy', $item) }}" class="btn btn-sm btn-danger btn-delete" data-toggle="tooltip" data-placement="top" title="Delete Insight"> <span class="fa fa-trash"></span></span>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="8" align="center">
                            @include('components.not-found-data')
                        </td>
                    </tr>
                    @endforelse
                  </table>
                </div>
                <div class="float-right">
                  {{ $insights->links() }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')

<script type="text/javascript">
    $('.btn-delete').on('click', function(){
        var href = $(this).attr('href');
        var title = $(this).data('title');
        swal({
          title: "Are you sure will delete data "+ title +" ?",
          text: "Once deleted the data cannot be restored !",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            $('#deleteForm').attr('action', href);
            $('#deleteForm').submit();
          }
        });
    });
    </script>
@endsection

resources/views/asset/insights/show.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('asset.insights.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Detail @lang('app.insights')</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item"><a href="#">Assets</a></div>
          <div class="breadcrumb-item"><a href="{{ route('asset.insights.index') }}">@lang('app.insights')</a></div>
          <div class="breadcrumb-item">{{ $insight->name }}</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">

              <div class="card-header">
                <h4>Data @lang('app.insights')</h4>
              </div>
              <div class="card-body">

              <!-- NAME -->
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.name')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $insight->name }}
                    </div>
                </div>

                <!-- CATEGORY -->
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.category')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $insight->category }}
                    </div>
                </div>

                <!-- DESCRIPTION -->
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.description')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $insight->description }}
                    </div>
                </div>

                <!-- MONTH -->
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.month')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $insight->month }}
                    </div>
                </div>

                <!-- YEAR -->
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.year')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $insight->year }}
                    </div>
                </div>

                <!-- FILE -->
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.file')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        <a href="{{ $insight->url_file }}" target="_blank">{{ $insight->file }}</a> 
                    </div>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection