routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::get('/users', function () {
    return view('chart.user', [
        'title' => 'Active user per day'
    ]);
});
Route::get('/userstotal', function () {
    return view('chart.usertotal', [
        'title' => 'Home'
    ]);
});
Route::get('/usersservices', function () {
    return view('chart.userservices', [
        'title' => 'Home'
    ]);
});
Route::get('/usersdatas', function () {
    return view('chart.usersdatas', [
        'title' => 'Home'
    ]);
});
Route::get('/usersrevenue', function () {
    return view('chart.userrevenue', [
        'title' => 'Home'
    ]);
});
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>'auth'], function(){
	Route::get('/', 'HomeController@index')->name('index');
	Route::get('/normalization/{data}', 'NormalizationController@index');
	Route::group(['prefix'=>'asset', 'as'=>'asset.'], function(){
		Route::resource('products','AssetProductController');
		Route::group(['prefix'=>'products/{product}', 'as'=>'products.'], function(){
			Route::resource('competitors','AssetProductCompetitorController');
		});
		Route::get('data-collections/generate', 'AssetDataCollectionController@generateData');
		Route::resource('data-collections','AssetDataCollectionController');
		Route::resource('models','AssetModelController');
		Route::resource('copy-rights','AssetCopyRightController');
		Route::resource('softwares','AssetSoftwareController');
		Route::resource('insights','AssetInsightController');
		Route::resource('clients','AssetClientController');
		Route::resource('reports','AssetReportController');
		Route::resource('clipping-onlines','AssetClippingOnlineController');
		Route::resource('domains','AssetDomainController');
	});

	Route::group(['namespace'=>'Operasional', 'prefix'=>'operational', 'as'=>'operational.'], function(){
		Route::resource('engine','EngineController');
		Route::resource('database','DatabaseController');
		Route::resource('groupserver','GroupServerController');
		Route::resource('server','ServerController');
		Route::resource('serverxgroup','ServerXGroupController');
		Route::resource('enginexdatabase','EngineXDatabaseController');
		Route::resource('enginexserver','EngineXServerController');
	});

	Route::group(['prefix'=>'ajax', 'namespace'=>'Ajax'], function(){
		Route::get('dashboard/chart-data-collection', 'DashboardController@chartDataCollectionV2');
		Route::get('dashboard/chart-valuasi', 'DashboardController@chartValuasi');
	});
});

app/Models/AssetModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\{Model, SoftDeletes};
use App\User;

class AssetModel extends Model
{
    use SoftDeletes;
    
    protected $guarded = [];

    public function scopeByUser($query, User $user)
    {
        // If role admin show all data
        if (!$user->isAdmin()) {
            return $query->where('user_id', $user->id);
        }

        return $query;
    }

    public function getValueLabelAttribute()
    {
        if($this->value){
            return 'Rp. '.number_format($this->value,2,",",".");
        }
    }
}

resources/views/asset/products/create.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('asset.products.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>@lang('app.add') @lang('app.product')</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">@lang('app.assets')</a></div>
          <div class="breadcrumb-item">@lang('app.add') @lang('app.product')</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Data @lang('app.product')</h4>
              </div>
              <div class="card-body">
                <form class="form" action="{{ route('asset.products.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.name')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('name') }}" name="name" class="@error('name') is-invalid @enderror form-control">
                            @error('name')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.description')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <textarea name="description" class="@error('description') is-invalid @enderror form-control" row="3">{{ old('description') }}</textarea>
                            @error('description')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.url')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('url') }}" name="url" class="@error('url') is-invalid @enderror form-control">
                            @error('url')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.debit')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="number" step="0.01" value="{{ old('debit') }}" name="debit" class="@error('debit') is-invalid @enderror form-control">
                            @error('debit')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.credit')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="number" step="0.01" value="{{ old('credit') }}" name="credit" class="@error('credit') is-invalid @enderror form-control">
                            @error('credit')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.value')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="number" step="0.01" value="{{ old('value') }}" name="value" class="@error('value') is-invalid @enderror form-control">
                            @error('value')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right"></label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

@section('js')
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/upload-preview/assets/js/jquery.uploadPreview.min.js') }}"></script>
<script>
    $.uploadPreview({
        input_field: "#image-upload",   // Default: .image-upload
        preview_box: "#image-preview",  // Default: .image-preview
        label_field: "#image-label",    // Default: .image-label
        label_default: "Pilih Foto",   // Default: Choose File
        label_selected: "Ganti Foto",  // Default: Change File
        no_label: false,                // Default: false
        success_callback: null          // Default: null
    });
  </script>
@endsection

resources/views/asset/products/edit.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('asset.products.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>@lang('app.edit') @lang('app.product')</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item"><a href="#">@lang('app.assets')</a></div>
          <div class="breadcrumb-item"><a href="{{ route('asset.products.index') }}">@lang('app.product')</a></div>
          <div class="breadcrumb-item">@lang('app.edit') {{ $product->name }}</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Data @lang('app.product')</h4>
              </div>
              <div class="card-body">
                <form class="form" action="{{ route('asset.products.update', $product->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.name')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('name', $product->name) }}" name="name" class="@error('name') is-invalid @enderror form-control">
                            @error('name')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.description')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <textarea name="description" class="@error('description') is-invalid @enderror form-control" row="3">{{ old('description', $product->description) }}</textarea>
                            @error('description')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.url')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('url', $product->url) }}" name="url" class="@error('url') is-invalid @enderror form-control">
                            @error('url')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.debit')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="number" step="0.01" value="{{ old('debit', $product->debit) }}" name="debit" class="@error('debit') is-invalid @enderror form-control">
                            @error('debit')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.credit')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="number" step="0.01" value="{{ old('credit', $product->credit) }}" name="credit" class="@error('credit') is-invalid @enderror form-control">
                            @error('credit')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.value')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="number" step="0.01" value="{{ old('value', $product->value) }}" name="value" class="@error('value') is-invalid @enderror form-control">
                            @error('value')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right"></label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

@section('js')
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/upload-preview/assets/js/jquery.uploadPreview.min.js') }}"></script>
<script>
    $.uploadPreview({
        input_field: "#image-upload",   // Default: .image-upload
        preview_box: "#image-preview",  // Default: .image-preview
        label_field: "#image-label",    // Default: .image-label
        label_default: "Pilih Foto",   // Default: Choose File
        label_selected: "Ganti Foto",  // Default: Change File
        no_label: false,                // Default: false
        success_callback: null          // Default: null
    });
  </script>
@endsection

resources/views/asset/products/index.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>@lang('app.product')</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">@lang('app.assets')</a></div>
          <div class="breadcrumb-item"><a href="#">@lang('app.product')</a></div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>@lang('app.list_of') @lang('app.product')</h4>
              </div>
              <div class="card-body">
                <div class="float-left d-flex">
                    <a href="{{ route('asset.products.create') }}" class="btn btn-primary">Add @lang('app.product')</a>
                </div>
                <div class="float-right">
                  <form action="" method="GET">
                    <div class="input-group">
                      <input type="text" class="form-control" name="search" placeholder="Search" value="{{ request()->search }}">
                      <div class="input-group-append">
                        <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                      </div>
                    </div>
                  </form>
                </div>

                <div class="clearfix mb-3"></div>

                <div class="table-responsive">
                  <table class="table table-striped">
                    <tr>
                      <th>No</th>
                      <th>@lang('app.name')</th>
                      <th>@lang('app.description')</th>
                      <th>@lang('app.value')</th>
                      <th>#</th>
                    </tr>
                    @forelse ($products as $item)
                    <tr>
                        <td>{{ (($products->currentPage()-1) * $products->perPage()) + $loop->iteration }}</td>
                        <td>
                          @if($item->url)
                            <a href="{{$item->url}}" target="_blank">{{ $item->name }}</a>
                          @else
                            {{ $item->name }}
                          @endif
                        </td>
                        <td>{{ $item->description }}</td>
                        <td>{{ $item->value_label }}</td>
                        <td>
                            <a href="{{ route('asset.products.competitors.index', $item) }}" class="btn btn-sm btn-dark" data-toggle="tooltip" data-placement="top" title="Lihat Data Competitor"> <span class="fa fa-flag"></span></a>
                            <a href="{{ route('asset.products.show', $item) }}" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Lihat Data Product"> <span class="fa fa-eye"></span></a>
                            <a href="{{ route('asset.products.edit', $item) }}" class="btn btn-sm btn-warning" data-toggle="tooltip" data-placement="top" title="Edit Product"> <span class="fa fa-edit"></span></a>
                            <span data-title="{{ $item->name }}" href="{{ route('asset.products.destroy', $item) }}" class="btn btn-sm btn-danger btn-delete" data-toggle="tooltip" data-placement="top" title="Delete Product"> <span class="fa fa-trash"></span></span>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="6" align="center">
                            @include('components.not-found-data')
                        </td>
                    </tr>
                    @endforelse
                  </table>
                </div>
                <div class="float-right">
                  {{ $products->links() }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')

<script type="text/javascript">
    $('.btn-delete').on('click', function(){
        var href = $(this).attr('href');
        var title = $(this).data('title');
        swal({
          title: "Are you sure will delete data "+ title +" ?",
          text: "Once deleted the data cannot be restored !",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            $('#deleteForm').attr('action', href);
            $('#deleteForm').submit();
          }
        });
    });
    </script>
@endsection

resources/views/asset/products/show.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('asset.products.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Detail @lang('app.product')</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item"><a href="#">Assets</a></div>
          <div class="breadcrumb-item"><a href="{{ route('asset.products.index') }}">@lang('app.product')</a></div>
          <div class="breadcrumb-item">{{ $product->name }}</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Data @lang('app.product')</h4>
              </div>
              <div class="card-body">
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.name')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $product->name }}
                    </div>
                </div>
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.description')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $product->description }}
                    </div>
                </div>
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.url')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $product->url }}
                    </div>
                </div>
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.debit')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $product->debit }}
                    </div>
                </div>
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.credit')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $product->credit }}
                    </div>
                </div>
                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.value')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $product->value_label }}
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection