routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::get('/users', function () {
    return view('chart.user', [
        'title' => 'Active user per day'
    ]);
});
Route::get('/userstotal', function () {
    return view('chart.usertotal', [
        'title' => 'Home'
    ]);
});
Route::get('/usersservices', function () {
    return view('chart.userservices', [
        'title' => 'Home'
    ]);
});
Route::get('/usersdatas', function () {
    return view('chart.usersdatas', [
        'title' => 'Home'
    ]);
});
Route::get('/usersrevenue', function () {
    return view('chart.userrevenue', [
        'title' => 'Home'
    ]);
});
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>'auth'], function(){
	Route::get('/', 'HomeController@index')->name('index');
	Route::get('/normalization/{data}', 'NormalizationController@index');
	Route::group(['prefix'=>'asset', 'as'=>'asset.'], function(){
		Route::resource('products','AssetProductController');
		Route::group(['prefix'=>'products/{product}', 'as'=>'products.'], function(){
			Route::resource('competitors','AssetProductCompetitorController');
		});
		Route::get('data-collections/generate', 'AssetDataCollectionController@generateData');
		Route::resource('data-collections','AssetDataCollectionController');
		Route::resource('models','AssetModelController');
		Route::resource('copy-rights','AssetCopyRightController');
		Route::resource('softwares','AssetSoftwareController');
		Route::resource('insights','AssetInsightController');
		Route::resource('clients','AssetClientController');
		Route::resource('reports','AssetReportController');
		Route::resource('clipping-onlines','AssetClippingOnlineController');
		Route::resource('domains','AssetDomainController');
	});

	Route::group(['namespace'=>'Operasional', 'prefix'=>'operational', 'as'=>'operational.'], function(){
		Route::resource('engine','EngineController');
		Route::resource('database','DatabaseController');
		Route::resource('groupserver','GroupServerController');
		Route::resource('server','ServerController');
		Route::resource('serverxgroup','ServerXGroupController');
		Route::resource('enginexdatabase','EngineXDatabaseController');
		Route::resource('enginexserver','EngineXServerController');
	});

	Route::group(['prefix'=>'ajax', 'namespace'=>'Ajax'], function(){
		Route::get('dashboard/chart-data-collection', 'DashboardController@chartDataCollectionV2');
		Route::get('dashboard/chart-valuasi', 'DashboardController@chartValuasi');
	});
});

app/Models/AssetReport.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\{Model, SoftDeletes};
use Storage;

class AssetReport extends Model
{
    use SoftDeletes;
    protected $guarded = [];

    public function getUrlFileAttribute()
    {
        if($this->file){
            return Storage::disk(config('app.disk'))->url($this->file);
        }
    }

    public function getFileNameAttribute()
    {
        if($this->file){
            $name = collect(explode("/", $this->file));
            return $name->last();
        }
    }

    public function client()
    {
        return $this->belongsTo(AssetClient::class, 'client_id');
    }
}

resources/views/asset/reports/create.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('asset.reports.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>@lang('app.add') @lang('app.reports')</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">@lang('app.assets')</a></div>
          <div class="breadcrumb-item">@lang('app.add') @lang('app.reports')</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Data @lang('app.reports')</h4>
              </div>
              <div class="card-body">
                <form class="form" action="{{ route('asset.reports.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <!-- CLIENT NAME -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.client_name')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <select class="form-control" name="client_id" required="">
                                <option value="">-</option>
                                @foreach($clients as $key => $item)
                                <option value="{{$item->id}}" {{ old('client_id') == $item->id ? 'selected' : ''}}>{{$item->name}}</option>
                                @endforeach
                            </select>
                            @error('client_id')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- TYPE -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.type')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            @php
                                $types = ['daily','weekly','monthly','report','insidental'];
                            @endphp
                            <select class="form-control" name="type" required="">
                                <option value="">-</option>
                                @foreach($types as $key => $item)
                                <option value="{{$item}}" {{ old('type') == $item ? 'selected' : ''}}>{{$item}}</option>
                                @endforeach
                            </select>
                            @error('type')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- DESCRIPTION -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.description')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <textarea name="description" class="@error('description') is-invalid @enderror form-control" row="3">{{ old('description') }}</textarea>
                            @error('description')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- START DATE -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.start_date')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="date" value="{{ old('start_date') }}" name="start_date" class="@error('start_date') is-invalid @enderror form-control">
                            @error('start_date')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- END DATE -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.end_date')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="date" value="{{ old('end_date') }}" name="end_date" class="@error('end_date') is-invalid @enderror form-control">
                            @error('end_date')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- FILE -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.file')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="file" value="{{ old('file') }}" name="file" class="@error('file') is-invalid @enderror form-control">
                            @error('file')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right"></label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>

                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

@section('js')
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/upload-preview/assets/js/jquery.uploadPreview.min.js') }}"></script>
<script>
    $.uploadPreview({
        input_field: "#image-upload",   // Default: .image-upload
        preview_box: "#image-preview",  // Default: .image-preview
        label_field: "#image-label",    // Default: .image-label
        label_default: "Pilih Foto",   // Default: Choose File
        label_selected: "Ganti Foto",  // Default: Change File
        no_label: false,                // Default: false
        success_callback: null          // Default: null
    });
  </script>
@endsection

resources/views/asset/reports/edit.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('asset.reports.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>@lang('app.edit') @lang('app.reports')</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item"><a href="#">@lang('app.assets')</a></div>
          <div class="breadcrumb-item"><a href="{{ route('asset.reports.index') }}">@lang('app.reports')</a></div>
          <div class="breadcrumb-item">@lang('app.edit') @lang('app.report') {{ optional($report->client)->name }}</div>
        </div>
      </div>
      
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Data @lang('app.reports')</h4>
              </div>
              <div class="card-body">
                <form class="form" action="{{ route('asset.reports.update', $report->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')

                    <!-- CLIENT NAME -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.client_name')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <select class="form-control" name="client_id" required="">
                                <option value="">-</option>
                                @foreach($clients as $key => $item)
                                <option value="{{$item->id}}" {{ old('client_id', $report->client_id) == $item->id ? 'selected' : ''}}>{{$item->name}}</option>
                                @endforeach
                            </select>
                            @error('client_id')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- TYPE -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.type')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            @php
                                $types = ['daily','weekly','monthly','report','insidental'];
                            @endphp
                            <select class="form-control" name="type" required="">
                                <option value="">-</option>
                                @foreach($types as $key => $item)
                                <option value="{{$item}}" {{ old('type', $report->type) == $item ? 'selected' : ''}}>{{$item}}</option>
                                @endforeach
                            </select>
                            @error('type')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- DESCRIPTION -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.description')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <textarea name="description" class="@error('description') is-invalid @enderror form-control" row="3">{{ old('description', $report->description) }}</textarea>
                            @error('description')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- START DATE -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.start_date')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="date" value="{{ old('start_date', $report->start_date) }}" name="start_date" class="@error('start_date') is-invalid @enderror form-control">
                            @error('start_date')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- END DATE -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.end_date')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="date" value="{{ old('end_date', $report->end_date) }}" name="end_date" class="@error('end_date') is-invalid @enderror form-control">
                            @error('end_date')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <!-- FILE -->
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.file')</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="file" value="{{ old('file') }}" name="file" class="@error('file') is-invalid @enderror form-control">
                            @error('file')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right"></label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

@section('js')
<script src="{{ asset('/stisla-2.2.0/dist/assets/modules/upload-preview/assets/js/jquery.uploadPreview.min.js') }}"></script>
<script>
    $.uploadPreview({
        input_field: "#image-upload",   // Default: .image-upload
        preview_box: "#image-preview",  // Default: .image-preview
        label_field: "#image-label",    // Default: .image-label
        label_default: "Pilih Foto",   // Default: Choose File
        label_selected: "Ganti Foto",  // Default: Change File
        no_label: false,                // Default: false
        success_callback: null          // Default: null
    });
  </script>
@endsection

resources/views/asset/reports/index.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>@lang('app.reports')</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">@lang('app.assets')</a></div>
          <div class="breadcrumb-item"><a href="#">@lang('app.reports')</a></div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>@lang('app.list_of') @lang('app.reports')</h4>
              </div>
              <div class="card-body">
                <div class="float-left d-flex">
                    <a href="{{ route('asset.reports.create') }}" class="btn btn-primary">Add @lang('app.reports')</a>
                </div>
                <div class="float-right">
                  <form action="" method="GET">
                    <div class="input-group">
                      <select class="form-control mr-2" name="client_id" onchange="this.form.submit()">
                        <option value="">Semua Client</option>
                        @foreach($clients as $item)
                        <option value="{{$item->id}}" {{ request()->client_id == $item->id ? 'selected' : ''}}>{{ $item->name }}</option>
                        @endforeach
                      </select>
                      <input type="text" class="form-control" name="search" placeholder="Search" value="{{ request()->search }}">
                      <div class="input-group-append">
                        <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                      </div>
                    </div>
                  </form>
                </div>

                <div class="clearfix mb-3"></div>

                <div class="table-responsive">
                  <table class="table table-striped">
                    <tr>
                      <th>No</th>
                      <th>@lang('app.client_name')</th>
                      <th>@lang('app.type')</th>
                      <th>@lang('app.start_date')</th>
                      <th>@lang('app.end_date')</th>
                      <th>@lang('app.description')</th>
                      <th>@lang('app.file')</th>
                      <th>Opsi</th>
                    </tr>
                    @forelse ($reports as $item)
                    <tr>
                        <td>{{ (($reports->currentPage()-1) * $reports->perPage()) + $loop->iteration }}</td>
                        <td>{{ optional($item->client)->name }}</td>
                        <td>{{ $item->type }}</td>
                        <td>{{ $item->start_date }}</td>
                        <td>{{ $item->end_date }}</td>
                        <td>{{ $item->description }}</td>
                        <td><a href="{{$item->url_file}}" target="_blank">{{ $item->file_name }}</a></td>
                        <td>
                            <a href="{{ route('asset.reports.show', $item) }}" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Lihat Detail Report"> <span class="fa fa-eye"></span></a>
                            <a href="{{ route('asset.reports.edit', $item) }}" class="btn btn-sm btn-warning" data-toggle="tooltip" data-placement="top" title="Edit Report"> <span class="fa fa-edit"></span></a>
                            <span data-title="" href="{{ route('asset.reports.destroy', $item) }}" class="btn btn-sm btn-danger btn-delete" data-toggle="tooltip" data-placement="top" title="Delete Report"> <span class="fa fa-trash"></span></span>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="8" align="center">
                            @include('components.not-found-data')
                        </td>
                    </tr>
                    @endforelse
                  </table>
                </div>
                <div class="float-right">
                  {{ $reports->links() }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')

<script type="text/javascript">
    $('.btn-delete').on('click', function(){
        var href = $(this).attr('href');
        var title = $(this).data('title');
        swal({
          title: "Are you sure will delete data "+ title +" ?",
          text: "Once deleted the data cannot be restored !",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            $('#deleteForm').attr('action', href);
            $('#deleteForm').submit();
          }
        });
    });
    </script>
@endsection

resources/views/asset/reports/show.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('asset.reports.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Detail @lang('app.reports')</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item"><a href="#">@lang('app.assets')</a></div>
          <div class="breadcrumb-item"><a href="{{ route('asset.reports.index') }}">@lang('app.reports')</a></div>
          <div class="breadcrumb-item">@lang('app.report') {{ optional($report->client)->name }}</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">

              <div class="card-header">
                <h4>Data @lang('app.reports')</h4>
              </div>
              <div class="card-body">

                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.client_name')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ optional($report->client)->name }}
                    </div>
                </div>

                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.type')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $report->type }}
                    </div>
                </div>

                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.start_date')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $report->start_date }}
                    </div>
                </div>

                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.end_date')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $report->end_date }}
                    </div>
                </div>

                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.description')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        {{ $report->description }}
                    </div>
                </div>

                <div class="form-group row align-items-center">
                    <label for="site-title" class="form-control-label col-sm-3 text-md-right">@lang('app.file')</label>
                    <div class="col-sm-6 col-md-9 col-lg-6">
                        <a href="{{ $report->url_file }}" target="_blank">{{ $report->file_name }}</a> 
                    </div>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection